### ISSUE TITLE
multilingual content

### ISSUE THREAD

**Issue by elf-pavlik** [okfde/2013.archiv.codefor.de#139]
i would like to help with making it possible to besides publishing content in german also to have english version. IMO in software world english language acts as [Lingua franca](https://en.wikipedia.org/wiki/Lingua_franca)

**Comment by elf-pavlik** [comment]
possibly useful links:
- http://developmentseed.org/blog/multilingual-jekyll-sites/
- http://nicoespeon.com/en/2014/04/multilingual-blog-with-jekyll-1-5/

**Comment by johnjohndoe** [comment]
:up:

**Comment by drewrwilson** [comment]
Great! Just saw this issue. @soniaskhan is actually already going through and translating content. @elf-pavlik @johnjohndoe still interested in making this happen?

**Comment by k-nut** [comment]
cleanup time! We implemented this quite a long time ago so I am closing this as done! Thank you for pointing it out elf, it was missing for too long! :)

**Comment by johnjohndoe** [comment]
How is the status with regards to the project descriptions? Can people create an English and a German version of the project description and switching happens automatically?
