### ISSUE TITLE
Events of all cities on front page

### ISSUE THREAD

**Issue by johnjohndoe** [okfde/2013.archiv.codefor.de#223]
The upcoming events of all cities should be displayed on the front page. This will make it easier to see what is going on in all the OK Labs.

**Comment by todendah** [comment]
Would be great, if all meetup.com-events were added automatically on the website. Active communities with weekly meetups do not need to add an event every week again.

**Comment by arduina** [comment]
Absolutely. We are planning to relaunch the website soon, so remarks like these are really helpful! Grain of salt: I won't be able to manage a relaunch before June, so if you have ideas on how to implement this feature, you are invited to give it a try. Just make sure you have some kind of feedback by the community.

**Comment by todendah** [comment]
@arduina Unfortunately I am not a coder, but I will try to research a bit in the next weeks. Maybe I find something useful!

**Comment by jfilter** [comment]
There is something here now: https://codefor.de/termine/

But the events from MeetUp are not included. So it's usually empty or only a couple of events are displayed. In the current state, people could think there arn't any events in e.g. Berlin. Maybe just hide it for now?

**Comment by derhuerst** [comment]
My opinion: Why would I want to know what's going on in *all* 25 labs, on the detail level of MeetUp? I'd rather:

1. encourage people to look at the page of their local lab, or
2. have a curated list with events with Germany-wide relevance.

Since 2 seems to be something the will stop working over time, I'm in favour of 1.
