### ISSUE TITLE
Search is missing.

### ISSUE THREAD

**Issue by almereyda** [okfde/2013.archiv.codefor.de#238]
Search will only work if GitHub's [automatic deployment via `gh-pages` branch is abandoned](http://jekyllrb.com/docs/plugins/) and seperated (self-rendered) branches for `source` and `gh-pages` are being used.

As an intermediary, @jochenklar, I could offer to deploy some CI so we run the plugins ourselves, after a Post Receive Hook has been triggered.

What'cha think?

**Comment by gitviola** [comment]
Hey @almereyda, is this issue still relevant? :)

**Comment by MorrisJobke** [comment]
2014 -> close
