### ISSUE TITLE
Sort "Termine" by date

### ISSUE THREAD

**Issue by ironjan** [okfde/2013.archiv.codefor.de#258]
Right now the events are unsorted/displayed as specified in [https://github.com/okfde/codefor.de/blob/gh-pages/_data/events.yml](events.yml). This leads to confusing arrangement of events, see screenshot. 

Unfortunately this issue cannot be solved by the "standard" sorting way and would need some adaptions to the event-model.
- `day-nr` and `month` should be merged into a yyyy-mm-dd formatted `date`
- The `events.html` needs to be adapted to use this date format by
  - splitting the date into $d, $m, $y
  - and construction `month` from $m and $y using a lookup table for "month names"

Is this wanted? Will someone take over this issue?

I could start working on it myself but that would take some time ;)

![default](https://cloud.githubusercontent.com/assets/1698836/5505743/ee4379e4-8793-11e4-8f89-2dabac52184e.png)

**Comment by streiten** [comment]
nevertheless we are heading towards meetup integration: 
- events are stored as a jekyll collection now (_termine)
- the event date/day/month/year is stored in a proper date string in front-matter now  (unfortunatley the date in filename seems not available for collections/pages)
- the eventlist is sorted
- past events are not beeing output (on build) 

@juliakloiber @arduina
