### ISSUE TITLE
Restructure HTML source

### ISSUE THREAD

**Issue by HerHde** [okfde/2013.archiv.codefor.de#301]
The HTML and CSS classes are a mess:
- Most pages do not have any `H1`-Tags, but `H2` and `H3` as first headline. The _oklabs_-Page for example has none at all.
- **Bootstrap**'s [structure](http://getbootstrap.com/css/#grid-intro) is often violated. [Bootlint](/twbs/bootlint) may help to check the errors.
  - There is no common theme defining the usage of the Bootstrap grid system
  - Why do we only use 10 of 12 columns? (+1 offset)
  - Sometimes jumbotrons are used, but under which conditions?
- There are many useless `div`s
- How about a sitemap?
- IMHO the padding is _too damn high_, I scrolled to death :-(

**Comment by gitviola** [comment]
now there is a sitemap: http://codefor.de/sitemap.xml :)

Also there is no _oklabs_-Page anymore

**Comment by jfilter** [comment]
Since there hasn't been a lot of activity, I will close this issue. If you want to improve the code, feel free to send PRs.
