### ISSUE TITLE
Markdown links don't work in projects overview (but in single project page)

### ISSUE THREAD

**Issue by metawops** [okfde/2013.archiv.codefor.de#332]
In a Lab's projects overview page, when the project description contains Markdown links, they don't work. See this screenshot: ![screen shot 2015-04-08 at 15 51 45](https://cloud.githubusercontent.com/assets/376090/7048421/4f782a54-de13-11e4-90d5-56c653c61d25.png)

The single project page, however, _can_ display the Markdown link correctly, as shown here:
![screen shot 2015-04-08 at 15 51 58](https://cloud.githubusercontent.com/assets/376090/7048483/a1dcaac2-de13-11e4-9de7-e42215133bf5.png)

**Comment by streiten** [comment]
fixed now!

**Comment by metawops** [comment]
Super! :+1:
