### ISSUE TITLE
München Defibrillatoren in OSM: Please add additional info

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#336]
Add link (if there is a link) 
Add photo
@MarHai

**Comment by MarHai** [comment]
there is none (yet)

**Comment by saerdnaer** [comment]
@MarHai Maybe a screenshot of https://umap.openstreetmap.fr/en/map/defi-munchen_29077 and a link to http://wiki.osm.org/München/Defi ?
