### ISSUE TITLE
München finder app: Please add additional info

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#337]
Is the defibrilatoren app an add-on to the finder app? Should it be its own project? 
@MarHai

**Comment by MarHai** [comment]
it should (as soon as it's finished) be an application out of the finder app. the latter is a generic framework that needs data in order to manifest an application.

**Comment by saerdnaer** [comment]
Hier mal ein Screenshot:
![image](https://cloud.githubusercontent.com/assets/40266/8002051/de83a6bc-0b6b-11e5-8f0d-737c12d3ada3.png)

**Comment by saerdnaer** [comment]
Da jetzt erledigt: Bitte schließen.
