### ISSUE TITLE
Magdeburg: Please add additional info

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#339]
Is Rechtegewalt still "in progress"?
@filter1

**Comment by jfilter** [comment]
Yes, I want to improve it. But it is possible to consider it as a 'working' project. Do you want me to change it? :)

**Comment by arduina** [comment]
@filter1 - wie wär's mit "Sucht Mitmacher"?  So wie: http://codefor.de/projekte/2014-03-22-hn-trinkwasser.html

**Comment by jfilter** [comment]
Ja, kann man machen. Wollt ihr das 'in progress' wegbekommen? ;)

**Comment by arduina** [comment]
Nicht unbedingt, aber "sucht Mitmacher" hat vielleicht einen höheren Informationswert für die geneigten LeserInnen, oder? :)

**Comment by johnjohndoe** [comment]
Related #159

**Comment by jfilter** [comment]
rechte gewalt is done. I updated the status in #825
