### ISSUE TITLE
Leipzig Kitas Verzeichnis: Link

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#346]
-Demo Link not found
@RicardoUsbeck

**Comment by RicardoUsbeck** [comment]
@DebVortex

**Comment by DebVortex** [comment]
Thanks for reporting this Issue! We already faced this problem a while ago but have just forgotten it. The Link to the demo link was created from a former leipzig member. I created a pull request and removed the link for now. We going to release the project, soon and then will update the link.
