### ISSUE TITLE
Hamburg: Kita Finder Photo 

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#347]
-Change photo for consistency

**Comment by gitviola** [comment]
@soniaskhan does this still needs to be fixed? If so: could you please add the link to the project? also, who can fix it?

Feel free to close this issue in case it has been fixed already

**Comment by MorrisJobke** [comment]
This is fixed: http://codefor.de/projekte/2014-04-27-hh-kitaKarte
