### ISSUE TITLE
Berlin Weihnachstmärkte: Link + Status

### ISSUE THREAD

**Issue by soniaskhan** [okfde/2013.archiv.codefor.de#349]
-Status: 'In progress'?
-Link: Only to github
@tursics

**Comment by tursics** [comment]
Stimmt. Werde ich ergänzen.

**Comment by johnjohndoe** [comment]
Related: #159

**Comment by gitviola** [comment]
Was ist damit, hat sich das erledigt? (@soniaskhan @tursics)

**Comment by tursics** [comment]
Ich habe das in https://github.com/okfde/codefor.de/pull/610 gefixt @schurig

**Comment by gitviola** [comment]
@tursics supi, danke
