### ISSUE TITLE
Typo im Code of Conduct

### ISSUE THREAD

**Issue by ironjan** [okfde/2013.archiv.codefor.de#399]
http://codefor.de/code-of-conduct/

Fehlerhaft: 
`Die Projektleitung von Code for Germany sollte informiert und einbezogen werden, um die ähnliche Konflikte in Zukunft besser lösen zu können.` 

Korrekt:

`Die Projektleitung von Code for Germany sollte informiert und einbezogen werden, um ähnliche Konflikte in Zukunft besser lösen zu können.`

(ein "die" ist zu viel).

**Comment by MorrisJobke** [comment]
PR is welcome ;)
