### ISSUE TITLE
Presse Links adden

### ISSUE THREAD

**Issue by juliakloiber** [okfde/2013.archiv.codefor.de#451]
http://www.sz-online.de/nachrichten/studenten-helfen-bei-der-parkplatzsuche-3128007.html
http://www.tagesspiegel.de/berlin/architekturfestival-makecity-in-berlin-wie-aktivisten-die-stadtplanung-transparenter-machen/11920360.html

**Comment by k-nut** [comment]
Live at http://codefor.de/presse/. Gut so? @juliakloiber
