### ISSUE TITLE
Stories translation to EN

### ISSUE THREAD

**Issue by streiten** [okfde/2013.archiv.codefor.de#467]
hey, the content is ready and i just wanted to quickly check back about how to implement this. @jochenklar, @juliakloiber told me you worked on the multilang so far. do you have some pointers on how to approach the stories ? currently it's a collection. i am thinking of setting up a new collection _storiesEN that renders to en/stories/ . do you think this will work or should the stories be moved to categorized pages ? thanks for your pointers
@flapperleenie

**Comment by flapperleenie** [comment]
Setting up _storiesEN should be okay, as far as I can tell! The content is ready, yes :)

**Comment by streiten** [comment]
ok, it's set up in the stories branch now! @flapperleenie could you please edit the docs in _stories_en and once everything is there we merge it to the gh-pages branch. sorry for the delay btw.

**Comment by jochenklar** [comment]
hi, I am currently on vacation in croatia. When I'm back I will look into it. If you don't hear from me next week, please remind me again.

Also @k-nut might add something to this.

cheers,
Jochen

**Comment by flapperleenie** [comment]
Hi again,
Somehow can't push the content, it keeps telling me "src refspec stories matches more than one". Is there a quick fix for this?
Cheers,
Eileen

**Comment by k-nut** [comment]
Hey @flapperleenie,
what did you run that gave you this output? Are you running from the terminal or do you use the guthub client? Did you make sure to commit before pushing?

Am 25. Juli 2015 17:50:07 MESZ, schrieb flapperleenie notifications@github.com:

> Hi again,
> Somehow can't push the content, it keeps telling me "src refspec
> stories matches more than one". Is there a quick fix for this?
> Cheers,
> Eileen
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/okfde/codefor.de/issues/467#issuecomment-124854703

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by flapperleenie** [comment]
Hi @k-nut,
I'm running the github client, did commit before I tried to push... Let me try terminal and get back to you!

**Comment by flapperleenie** [comment]
Apologies for the delay (and the redundant commits), turns out I just had to delete the tag 'stories' to push because it's ambiguous :)

**Comment by streiten** [comment]
sorry, the 'stories' tag was probably my fault. anyhow, it's fixed now and i just merged the stories branch to gh-page - so the english version is live. looks to me everything is working as expected. @jochenklar , @k-nut should you have any recommendations for the code/approach please reopen and let me know!
