### ISSUE TITLE
Beginners Info

### ISSUE THREAD

**Issue by MorrisJobke** [okfde/2013.archiv.codefor.de#506]
Ich hab hier einen Link: https://docs.google.com/document/d/11zGFROsyVcHeJDA0YKJZQRZjZfCN4V_uCnTbu4rYgHg/edit

Da sollen laut @juliakloiber erstmal die Infos für Neulinge rein. Doch wo soll ich den Link jetzt auch die Webseite setzen? Es soll ja für generelle Fragen herhalten können und deshalb sehr präsent sein.

**Comment by MorrisJobke** [comment]
Das ist quasi unser "Wiki" ;)

**Comment by gitviola** [comment]
@MorrisJobke @juliakloiber hmm, ich stoße irgendwie auch nur alle 3 Monate mal wieder auf dieses Dokument.

Also hier gibt es ja auch ein [Wiki](https://github.com/okfde/codefor.de/wiki), vielleicht können wir das da verlinken? Unter einem Punkt wie `Wichtige Links` vielleicht?

---

_Bin dabei alle Issues durchgehen, damit nicht so viel hängen bleibt. Daher, können wir das irgendwie abschließen oder lieber schließen?_

**Comment by MorrisJobke** [comment]
> Also hier gibt es ja auch ein Wiki, vielleicht können wir das da verlinken? Unter einem Punkt wie Wichtige Links vielleicht?

Feel free to do so :) Ich mag den Ansatz, dass wir das öffentlicher verlinken :)

**Comment by gitviola** [comment]
@MorrisJobke habs mal direkt auf der Wiki Startseite verlinkt. :)

Wollen wir dieses Issue dann erstmal schließen?
