### ISSUE TITLE
"Rückblick 2014" aus Header entfernen.

### ISSUE THREAD

**Issue by k-nut** [okfde/2013.archiv.codefor.de#541]
Jetzt ist schon 2016 aber im Header ist immer noch der Rückblick für 2014 verlinkt.

Ich finde, dass das ein bisschen unaktuell wirkt und wir es zumindest da oben entfernen sollten.

Meinungen?!

**Comment by johnjohndoe** [comment]
:+1:

**Comment by k-nut** [comment]
Jetzt wo der neue Rückblick da ist, ist das ja geklärt :)
