### ISSUE TITLE
assets/blog/muenchen

### ISSUE THREAD

**Issue by digisus** [okfde/2013.archiv.codefor.de#55]
Bitte den Ordner assets/blog/muenchen anlegen.

Oder mir kurz sagen, wie das geht, konnte nichts finden, bin aber auch neu als aktiver github User. :-)

Danke,
Marcus

**Comment by symptog** [comment]
Hallo,

hast du schonmal mit git gearbeitet?
gute kurze anleitung -> http://rogerdudler.github.io/git-guide/index.de.html

wozu brauchst du das verzeichnis?

grüße
tobi

**Comment by MorrisJobke** [comment]
@digisus Du kannst die Inhalte direkt bei dir lokal im Git anlegen und als Pull Request für dieses Repo einstellen.

**Comment by saerdnaer** [comment]
@digisus Die Sache hat sich inzwischen erledigt, oder?
