### ISSUE TITLE
Add Slack to website

### ISSUE THREAD

**Issue by johnjohndoe** [okfde/2013.archiv.codefor.de#552]
Add Slack to website so new people can find it easily.
https://openknowledgegermany.slack.com

**Comment by arduina** [comment]
Hm, meinst du? Eigentlich ist das ja ein "closed" Team, zu dem man ohnehin erst eingeladen werden muss. m.E. liegt das Einladen neuer Leute in der Verantwortung der Lab Leads, die ja auch alle Admins sind.

**Comment by gitviola** [comment]
Ich war selbst erst dafür. Aber da die Mehrzahl der Besucher nichts damit anfangen können, da sie erst eine Einladung bräuchten, ist es glaube besser die Aufklärung über das Slack-Team innerhalb der Labs zu belassen.

Vielleicht können die Labs auf ihre Lab-Unterseite anmerken, dass es die Möglichkeit dazu gibt. Aber was besseres fällt mir gerade nicht ein.
@johnjohndoe gib mir Bescheid, falls ich das Issue schließen kann

**Comment by johnjohndoe** [comment]
Meinetwegen.
