### ISSUE TITLE
Update profile pictures shown for members

### ISSUE THREAD

**Issue by konstin** [okfde/2013.archiv.codefor.de#645]
Ideally, this should be done daily by a cron job or something similar.

**Comment by MorrisJobke** [comment]
@konstin or simply run the script while adding the user to the list ;)

**Comment by MorrisJobke** [comment]
I ran the script and it imported one avatar: 063dbfa

I would go for a manual thing, because the cron job also needs to be checked if it still works and needs also some maintenance.
