### ISSUE TITLE
Liquid Errors nach Jekyll Update

### ISSUE THREAD

**Issue by ffalt** [okfde/2013.archiv.codefor.de#681]
Hi, nach dem Update von Jekyll in #680 werden so einige Liquid Syntax Fehler ausgegeben, weswegen die Seite auf dem OKF-Server nicht mehr aktualisiert wird.

```
Liquid Warning: Liquid syntax error (line 22): Unexpected character   in "link in page.links | limit: 1" in /_layouts/story.html
    Liquid Warning: Liquid syntax error (line 28): Unexpected character   in "image in page.header-images | limit: 1" in /_layouts/story.html
    Liquid Warning: Liquid syntax error (line 30): Unexpected character   in "{{ image.caption }}" in /_layouts/story.html
[snip]
```
Da hat sich im Format einiges geändert
https://jekyllrb.com/docs/upgrading/2-to-3/

Diese Warnungen kann der Server nicht ignorieren und sollte es wahrscheinlich auch nicht.

**Comment by ffalt** [comment]
Mmh. im obigen Link steht nicht viel zu Liquid. Für die ersten zwei Zeilen der Warnungen hat [hier](https://github.com/jekyll/jekyll/issues/3559) jemand die korrekte Liquid Syntax bei einem ähnlichen Problem angegeben.

**Comment by michael-k** [comment]
I'll look into it.  For now I reverted the last two commits in 7538477.
