### ISSUE TITLE
Scrolling unterhalb der Karte auf Smartphone nur schwer möglich

### ISSUE THREAD

**Issue by MorrisJobke** [okfde/2013.archiv.codefor.de#69]
Mir ist vorhins aufgefallen, dass man nicht unterhalb der Karte kommt, wenn man mit dem Smartphone browst. Man kann nicht weiterscrollen, weil man in der Karte scrollt und zurück geht auch nicht, weil die Karte den ganzen Bildschirm einnimmt.

Wenn man schnell scrollt und die Karte überscrollt wird, geht es.

**Comment by streiten** [comment]
ok :-( 
wir schauen mal - a.s.a.p.

**Comment by MorrisJobke** [comment]
War mir nur so mal aufgefallen. Ich hab ein Galaxy Nexus (1280 × 720 Pixel) und es ist mir im Hochformat passiert.
