### ISSUE TITLE
Karte: Klick auf Label vs Pin (Gmap -> OSM Migration) 

### ISSUE THREAD

**Issue by fnogatz** [okfde/2013.archiv.codefor.de#70]
Auf der Karte ist es möglich, sowohl per Klick auf das Label als auch den Pin zum entsprechenden OK Lab zu gelangen. Komisch wird's aber an den Stellen, wo sich Labels und Pins überschneiden: Die Labels überlagern zwar die Pins, dennoch führt einen ein Klick auf den Überschneidungsbereich auf das Ziel des Pins. Bsp Label OK Lab Ulm, wo der Pin für München drunter liegt.

Oehm, ist das Problem klar geworden? ^^

**Comment by mattfullerton** [comment]
Nicht so hilfreichen Vorschlag: auf Leaflet umsteigen :D

Hilfreicher:
Problem, mappane vs. floatpane:
http://stackoverflow.com/questions/13211655/google-maps-v3-infobox-zindex-not-functional#answer-13216458

Lösung, BoxOptions ändern(?):
https://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/docs/examples.html

**Comment by chk1** [comment]
MIttel- oder Rechtsklick auf einen Pin oder Label funktioniert leider ebenfalls nicht.
Auch dafür scheint es ein paar Workarounds zu geben:
http://stackoverflow.com/questions/8317949/how-to-make-a-google-maps-marker-a-simple-url-link
http://stackoverflow.com/questions/9481476/javascript-click-event-for-any-google-maps-markers

Der Umstieg auf Leaflet wäre ansonsten nicht so schwer. Ich wüsste nur grad keinen (kostenlosen) Tile-Service, der einen ähnlichen Kartenstil anbietet.

**Comment by PatrickStotz** [comment]
Hier ein Vorschlag um die Usability-Probleme zu lösen und gleichzeitig auf Leaflet + OSM basemaps umzustellen:
https://dl.dropboxusercontent.com/u/54512470/codeforde_map/index.html

Ich krieg das leider nicht in einen pull request zusammengefügt, aber eigentlich müsste das mit der Grundlage recht fix zu machen sein.

**Comment by MorrisJobke** [comment]
@PatrickStotz Sieht spitze aus! :+1:

**Comment by johnjohndoe** [comment]
:+1:  für OpenStreetMaps, super @PatrickStotz

**Comment by streiten** [comment]
@PatrickStotz gibt es die Möglichkeit beim Styling noch etwas ins Detail zu gehen um näher am ursprünglichen Design zu bleiben ? d.h:
- Wasser blau
- Gebäude und Strassen in unterschiedlichen grau Abstufungen
  Gerade bei den Lab-Maps (z.b. http://codefor.de/stuttgart/index.html) war uns das wichtig, da die Karte dann einen visuellen Fingerprint der Stadt darstellt und die unterschiedlichen Labpages auch above the fold wirklich unterschiedlich aussehen. 
- hinter dem Marker liegt noch irgendwie ein Dreieck/Pfeil
- können die Labels auch verlinkt werden ?

**Comment by PatrickStotz** [comment]
Hmm, an den Styles der Hintergrundkarte (Wasserfarbe, Gebäude) kann man leider nichts drehen. Sind ja vorgerenderte Maptiles (und selbst welche zu erstellen wäre mit zu aufwändig)
Ich hatte ganz vergessen dass die Karten auch für die Städteseiten genutzt werden. Hab die Zoombegrenzung in meiner Karte jetzt angepasst. So sieht man beim nah ran zoomen das Straßenraster. Allerdings kein Gebäude.
Das Dreieck gehört zu dem semi-transparenten Label-Hintergrund. Ich schau mal ob ich das noch los werde.

Link auch auf die Labels legen geht auf jeden Fall, ging auf die Schnelle aber über meine Javascript-Fähigkeiten hinaus

**Comment by PatrickStotz** [comment]
So, ich konnte die Dreiecke durch Anpassen der leaflet.label.css loswerden. Zudem liegen jetzt Links zu codefor.de auf allen Labels & Pins. Das Ganze sollte auf jeden Fall vor der Integration auf Browserkompatibilität etc. geprüft werden. Bei mir ist JavaScript nicht viel mehr als trial & error...
Ach ja, die neuen Labs habe ich auch integriert: https://dl.dropboxusercontent.com/u/54512470/codeforde_map/index.html

![bildschirmfoto 2015-01-11 um 15 45 25](https://cloud.githubusercontent.com/assets/2346483/5694371/33be440a-99a9-11e4-8bd1-62c2cd5655d5.png)

**Comment by MorrisJobke** [comment]
@PatrickStotz Dresden fehlt ;)

**Comment by chk1** [comment]
Was den Karstenstil angeht gibt es ein paar Möglichkeiten, z.B. selbst kreiren und dann von Mapbox hosten lassen. 

Oder selber einen Stil erstellen und rendern lassen, z.B. hiermit: https://github.com/ubergesundheit/ma-tiles. Ist ein fertiger Docker-Container der alles mitliefert, man muss noch einen API-Key von Mapbox haben (kostenlos bis zu einer bestimmten Anzahl an Anfragen, ich denke mit Caching kommt man mit einem kostenlosen Apikey ganz gut aus) damit die OSM Daten im Vector Format pro Tile bezogen werden können. Sicherlich könnte man auch einen OSM Datendump da irgendwie reinladen und wäre damit komplett unabhängig, braucht allerdings etwas Platz auf der Platte.

**Comment by MorrisJobke** [comment]
@chk1 oder wir nehmen einfach unseren eigenen Tileserver, der schon für Code for Germany existiert ,)

**Comment by chk1** [comment]
@MorrisJobke klingt gut :+1:

**Comment by MorrisJobke** [comment]
Wenn es den Style der Tiles gibt,  braucht man das ja "nur" anpassen. Ist auf jeden Fall einfacher als die sich komplett neu aus den Fingern zu ziehen ;)

**Comment by moklick** [comment]
Um Platz zu sparen und die Karte übersichtlicher zu gestalten, könnte man "OK Lab" bei den Labels weglassen und dann sowas wie "OK Labs" über die Karte schreiben.

**Comment by streiten** [comment]
wir haben das jetzt mal noch auf googlemaps angepasst...

**Comment by PatrickStotz** [comment]
@MorrisJobke: Oh stimmt, Dresden war mir durch gerutscht
@RU-Alex: Von der Usability her passt das jetzt wieder.

Die Optik finde ich bei der Google Basemap eher so lala, aber das ist wohl Geschmacksache. Mein Ansatz war die Kombi CartoDB Positron + Stamen Toner Lines. Eben weil ich den Aufwand eigene Tiles zu stylen & zu hosten vermeiden wollte. Der Style von Toner findet sich hier: https://github.com/aaronlidman/Toner-for-Tilemill bzw. hier: https://github.com/Citytracking/toner, der von Positron ist meines Wissens nicht veröffentlicht. Also wenn jemand Zeit & Lust haben sollte einen eignen Basemap style zu bauen, gerne :+1:

**Comment by streiten** [comment]
Wir haben jetzt dbzgl. Untersützung bei uns im Team und könnten dir Migration jetzt angehen. 
Oder möchte das jemand von euch machen ? 
@MorrisJobke @PatrickStotz @juliakloiber

**Comment by PatrickStotz** [comment]
Sorry, bin gerade in Neuseeland unterwegs und dementsprechend selten online. Klar, macht ruhig und übernehmt einfach von meinem Vorschlag was immer euch nützlich erscheint.

**Comment by streiten** [comment]
Wir haben jetzt den aufs Design optimierten Mapsstyle (https://api.tiles.mapbox.com/v4/codeforgermany.cc5365b0/page.html?access_token=pk.eyJ1IjoiY29kZWZvcmdlcm1hbnkiLCJhIjoiMVg2ZGdSSSJ9.JsM4S0LZpeNmI1rHQnCxig#9/51.7636/10.9616), aber noch keine Zeit die Marker & Lables zu integrieren. Hier ist auch keiner so richtig mit der OpenStreetMaps/Leaflet API vertraut - könnte das jemand von euch übernehmen ? 
@PatrickStotz @MorrisJobke @HerHde

**Comment by jongleur1983** [comment]
ich werd mal gucken, ob ich am Wochenende dazu komme, mir das näher anzugucken.

**Comment by chk1** [comment]
Ich hab mich mal daran versucht:
 23927c78c78a477cf2b4ee7aab6cf2bcf9d152d0

In Kürze:
- basiert auf der Demo von @PatrickStotz oben
- der Mapstyle von @RU-Alex ist drin
- verwendete Plugins sind `Leaflet.Label` und `Leaflet.awesome-markers`
- alle Scripte von externen CDNs
- bisher nur Code für die Übersichtskarte auf der Hauptseite

Was mir irgendwie Kopfschmerzen bereitet sind die Label: Ich bekomm es nicht hin, dass gleichzeitig der Marker in den Vordergrund kommt, wenn man die Maus auf dem Label hat. 

Andersherum ist das kein Problem (Maus auf Marker, Label kommt in den Vordergrund) mit der `riseOnHover` Option für Marker.

Ansonsten, wenn man die Labels von Leipzig, Jena, Dresden und Chemnitz etwas dreht, passt das vielleicht sogar wieder.

![screenshot from 2015-02-19 22 50 00](https://cloud.githubusercontent.com/assets/828496/6276889/58cf9866-b88a-11e4-8b2c-fb6a8b2465c6.png)

**Comment by chk1** [comment]
Mein Pullrequest ist ja nun einen Monat her und inzwischen wurden wieder Sachen an der Karte geändert (blaue Symbole und Legende), hat sich sonst noch was verändert oder ist was geplant? 

Vielleicht könnte erst die Leafletkarte übernommen werden, bevor weiter verändert wird, weitere Konflikte reinmergen ist ja eine recht aufwändige Prozedur. Falls was mit dem PR nicht ok ist bitte sagen.

**Comment by streiten** [comment]
oh nein, das muss ich mich entschuldigen! das ist etwas blöd gelaufen... erst keine zeit mir das an zu schauen - dann musste es super schnell gehen mit den änderungen/blauen markern für hack your city. (die sollen bis ende des jahres bleiben) ich schau gleich mal ob ich das gemerged und vielleicht selbst aktualisiert kriege...

**Comment by chk1** [comment]
Ok kein Problem :) Kann am Wochenende auch nochmal drüberschauen

**Comment by streiten** [comment]
bye bye gmaps, hello osm (ist gemerged)!

**Comment by johnjohndoe** [comment]
:+1: Vielen Dank, sehr geil.
