### ISSUE TITLE
Lizenz nicht im Repository angegeben, Lizenz für Code fehlt

### ISSUE THREAD

**Issue by keimlink** [okfde/2013.archiv.codefor.de#89]
Im Repository ist eine Lizenz nicht angegeben. Die Datei `LICENSE.md` im obersten Verzeichnis des Repositories ist die vom HTML5 Boilerplate. Das liegt daran, dass die Dateien des HTML5 Boilerplate einfach in das oberste Verzeichnis des Repositories abgekippt wurden. In der Datei `impressum.html` steht, dass die Inhalte der Seite unter einer Creative Commons CC by 4.0 Lizenz stehen.

Daraus ergeben sich verschiedene Probleme:
1. Alle Dateien einfach im obersten Verzeichnis des Repositories "abzukippen" macht es unübersichtlich und führt zu Problemen mit Lizenzen von Third-Party-Software, wie z.B. HTML5 Boilerplate. Die Dateien für die Site sollten also in ein Unterverzeichnis verschoben werden.
2. Die Lizenz für die Inhalte ist nur in `impressum.html` zu finden. Diese sollte aber auch mindestens in der `README.md` angegeben sein.
3. Es gibt keine Lizenz für den Code. Eine Creative Commons ist nicht gut für Code geeignet. Hier wäre eine Lizenz zu wählen, die mit denen der eingesetzen Third-Party-Software kompatibel ist.

**Comment by ironjan** [comment]
Aktuell halten mich die oben genannten Probleme (insbesondere fehlende Lizenz für Code) davon ab, das Layout für unsere OK Lab Seite zu übernehmen - corporate design ;)

**Comment by almereyda** [comment]
Bitte mal #240 #241 #242 und #243 auschecken. Wmgl. hilft die neue `CONTRIBUTING.md` ein wenig Licht ins Dunkel zu bringen.

Ich möchte empfehlen dem Umstand **1.** auch ein eigenes Issue zu widmen, ganz à la _Spätjahrsputz_ ... qua reenemachen bevor [zum Fest](http://24pullrequests.com) die Verwandtschaft antanzt ...

**Comment by gitviola** [comment]
Das issue ist jetzt schon sehr alt _(bin gerade im cleanup-Modus)_. Bekommen wir das noch gelöst?

@keimlink @ironjan

**Comment by ironjan** [comment]
Da codeforpb zwischenzeitlich auf codefor.de umgezogen und nun inaktiv ist, hat sich das Problem für mich erledigt. Dennoch würde ich das Einfügen der Lizenz ins Repo empfehlen, damit man einfach sieht, was wie wiederverwendet werden darf.

**Comment by keimlink** [comment]
Ich kann nicht mehr tun, als auf die Probleme aufmerksam zu machen und Lösungen vorzuschlagen. Die Entscheidung muss IMO jemand von der @okfde treffen.

**Comment by jfilter** [comment]
Können wir bitte einfach z.B. die MIT-Lizenz nehmen und das Issue schließen?

Ich glaube allen Beteiligten ist klar, dass dieses Repo nicht **das** Referenz-Projekt für Webseitengestaltung im Jahre 2018 ist. Es geht ja hier ein wenig *um's Prinzip* (welches ich befürtworte).
